name: MAIN_DEPLOY

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ukuq/onepoint
        path: onepoint
    - uses: actions/setup-node@v1 # 安装nodejs，版本指定10
      with:
        node-version: '10.x'
    - name: read config.json from secrets
      env: 
        CONFIG_JSON: ${{ secrets.CONFIG_JSON }} # secrets 提供
      run:
        echo $CONFIG_JSON > ./onepoint/config.json
    - name: install nowsh CLI and deploy
      env: 
        TOKEN: ${{ secrets.NOWSH_TOKEN }} # secrets 提供
      run: |
        sudo npm i -g now
        mkdir -p ./now/onepoint
        cp -r ./onepoint/ ./now/onepoint/api/
        cp ./onepoint/test/nowsh/now.json ./now/onepoint
        cd now/onepoint
        now --token $TOKEN --confirm
        cd ../../
